---
grails:
    profile: rest-api
    codegen:
        defaultPackage: org.olf.license
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
        multiTenancy:
            mode: SCHEMA
            tenantResolverClass: com.k_int.okapi.OkapiTenantResolver    # See src/main/groovy

    plugin:
      springsecurity:
        providerNames:
          - 'okapiAuthenticationProvider'

        controllerAnnotations:
          staticRules:
            -
              pattern: '/okapi/**'
              access:
                - 'permitAll' # SHould maybe lock this down to the Super tenant once it is properly enforced?
            -
              pattern: '/application/**'
              access:
                - 'permitAll'
            -
              pattern: '/**'
              access:
                - 'permitAll'
        filterChain:
          chainMap:
            - 
              pattern: '/**'
              filters: 'JOINED_FILTERS,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter,-basicAuthenticationFilter'
    databinding:
        dateFormats:
          - 'yyyy-MM-dd HH:mm:ss.S'
          - "yyyy-MM-dd'T'hh:mm:ss'Z'"
          - 'yyyy-mm-dd'

info:
    app:
        name: 'mod-directory'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
management:
    security:
        enabled: true
    endpoints:
        enabled-by-default: true
        jmx:
            enabled: true
        health:
            enabled: true
            db:
                enabled: true
            defaults:
                enabled: true
        info:
            enabled: true
        configprops:
            enabled: true
        loggers:
            enabled: true
        web:
            exposure:
                include: 'health,info'


---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
    allow_update_outside_transaction: true 


dataSource:
  pooled: true
  jmxExport: false
  dbCreate: none
  username: "${db.username:folio_admin}"
  password: "${db.password:folio_admin}"
  driverClassName: org.postgresql.Driver
  dialect: com.k_int.hibernate.dialects.postgres.KIPostgres94Dialect
  url: "jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.database:okapi_modules}?ApplicationName=mod-directory"
  schemaHandler: com.k_int.okapi.OkapiSchemaHandler
  properties:
    initialSize: 5
    maxActive: ${db.maxpoolsize:15}
    minIdle: 5
    maxIdle: 10
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1
    validationInterval: 30000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    removeAbandoned: true
    removeAbandonedTimeout: 60
    abandonWhenPercentageFull: 50
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
    dbProperties:
      ApplicationName: mod-directory


events:
  consumer:
    zk:
      connect: 'localhost:2181'
    bootstrap:
      servers: 'localhost:29092'
    key:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value:
      deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group:
      id: ModDirectoryConsumer

  publisher:
    zk:
      connect: 'localhost:2181'
    bootstrap:
      servers: 'localhost:29092'
    key:
      serializer: org.apache.kafka.common.serialization.StringSerializer
    value:
      serializer: org.apache.kafka.common.serialization.StringSerializer


environments:
  test:
    dataSource:
      url: "jdbc:postgresql://${db.host:localhost}:${db.port:54321}/${db.database:okapi_modules}?ApplicationName=mod-directory-test"
      properties:
        initialSize: 7
        minIdle: 2
        maxIdle: 10
        maxActive: 10
        validationQuery: SELECT 1
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED


  dbGen:
    grails:
      gorm:
        multiTenancy:
          mode: SCHEMA
          tenantResolverClass: org.grails.datastore.mapping.multitenancy.resolvers.SystemPropertyTenantResolver # System prop of gorm.tenantId 
      plugin:
        databasemigration:
          changelogFileName: module-tenant-changelog.groovy
    gorm:
      tenantId: public # Used by SystemPropertyTenantResolver

okapi:
  schema:
    appName: 'mod-directory'
  service:
    host: localhost
    port: 9130
    register: false
    deploy: false

folio:
  directory:
    defualtttl: "${folio.directory.defaultttl:120000}"  # min TTL in milliseconds for a directory entry to live before it can be tested for an updated - 2 mins
