#! /bin/sh
USAGE="Usage: `basename $0` [-h] [-o okapiURL] [-t tenant] [-u username] [-p password] uri"
# e.g. ./okapi-cmd -o https://okapi-reshare.apps.k-int.com -t reshare -u admin -p rE0gNx7m2o "/directory/refdata/DirectoryEntry/Status"

OKAPI="http://localhost:9130"
TENANT="diku"
UN="diku_admin"
PW="admin"

# Parse command line options.
while getopts ho:u:p:t: OPT; do
  case "$OPT" in
    h)
      echo $USAGE
      exit 0
      ;;
    o)
      OKAPI=$OPTARG
      ;;
    t)
      TENANT=$OPTARG
      ;;
    u)
      UN=$OPTARG
      ;;
    p)
      PW=$OPTARG
      ;;
    \?)
      # getopts issues an error message
      echo $USAGE >&2
      exit 1
      ;;
  esac
done

# Remove the options we parsed above.
shift `expr $OPTIND - 1`

# We want one non-option argument.
if [ $# -ne 1 ]; then
  echo $USAGE >&2
  exit 1
fi

# Access additional arguments as usual through
# variables $@, $*, $1, $2, etc. or using this loop:
URI=$1

AUTH_TOKEN=$(curl -sSL -D - -X POST -H 'accept: application/json' -H 'Content-type: application/json' \
    -H "X-Okapi-Tenant: $TENANT" --connect-timeout 5 --max-time 30 -d "{ \"username\":\"${UN}\", \"password\": \"${PW}\" }" \
    "${OKAPI}/authn/login" | grep -Fi x-okapi-token | sed 's/.*: *//;s/.$//' | xargs)
curl -sSL -XGET -H "X-Okapi-Token: ${AUTH_TOKEN}" -H 'accept: application/json' -H 'Content-type: application/json' \
  -H "X-Okapi-Tenant: $TENANT" --connect-timeout 5 --max-time 30 "${OKAPI}${URI}"
exit 0
