#! /bin/sh
USAGE="Usage: `basename $0` [-h] [-u username] [-p password] [-t tenant]"

if true; then
    TENANT="diku"
    UN="diku_admin"
    PW="admin"
    OKAPI="http://localhost:9130"
else
    TENANT="reshare"
    UN="admin"
    PW="rE0gNx7m2o"
    OKAPI="https://okapi-reshare.apps.k-int.com"
fi

# Parse command line options.
while getopts hupt: OPT; do
  case "$OPT" in
    h)
      echo $USAGE
      exit 0
      ;;
    u)
      UN=$OPTARG
      ;;
    p)
      PW=$OPTARG
      ;;
    t)
      TENANT=$OPTARG
      ;;
    \?)
      # getopts issues an error message
      echo $USAGE >&2
      exit 1
      ;;
  esac
done

# Remove the options we parsed above.
shift `expr $OPTIND - 1`

AUTH_TOKEN=$(curl -sSL -X POST -H 'accept: application/json' -H 'Content-type: application/json' \
    -H "X-Okapi-Tenant: $TENANT" --connect-timeout 5 --max-time 30 -d "{ \"username\":\"${UN}\", \"password\": \"${PW}\" }" \
    "${OKAPI}/authn/login" | jq -rc '.okapiToken' | sed 's/.*: *//' | xargs)
echo $AUTH_TOKEN
exit 0
